services:
  backend:
    build: .
    container_name: lg-st-ws-backend-service
    environment: 
      - "BOT_NAME=IRC Bot"
      - "WS_HOST=lg-st-ws-backend-service"
      - "WS_PORT=8000"
      - "CUSTOM_INSTRUCTIONS="
      - "MODEL_NAME=gpt-4.1"
      - "OPENAI_API_KEY=${OPENAI_API_KEY}"  # Ensure this is set in your .env file
    networks:
      - lg-st-ws-network
    command: ["uvicorn", "lg_st_ws.backend.server:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: .
    container_name: lg-st-ws-frontend-service
    environment: 
      - "BOT_NAME=IRC Bot"
      - "WS_HOST=lg-st-ws-backend-service"
      - "WS_PORT=8000"
      - "CUSTOM_INSTRUCTIONS="
      - "MODEL_NAME=gpt-4.1"
      - "OPENAI_API_KEY=${OPENAI_API_KEY}"  # Ensure this is set in your .env file
    ports:
      - "8001:8001"
    networks:
      - lg-st-ws-network
    command: ["python", "-m", "streamlit", "run", "/home/appuser/lg_st_ws/frontend/client.py", "--server.port", "8001", "--server.address", "0.0.0.0", "--server.headless", "true"]

networks:
  lg-st-ws-network:
      driver: bridge
